In [1]:
# Import libraries and modules
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Load data
# dataset_url = '/kaggle/input/covid19-symptoms-checker/Cleaned-Data.csv'
dataset_url = './Cleaned-Data.csv'
data = pd.read_csv(dataset_url, sep=';')

# Preparing columns
data[['Fever', 'Tiredness','Dry-Cough','Difficulty-in-Breathing','Sore-Throat','None_Sympton','Pains','Nasal-Congestion','Runny-Nose','Diarrhea','None_Experiencing','Age_0-9','Age_10-19','Age_20-24','Age_25-59','Age_60+','Gender_Female','Gender_Male','Gender_Transgender','Severity_Mild','Severity_Moderate','Severity_None','Severity_Severe','Contact_Dont-Know','Contact_No','Contact_Yes','Country']] = data['Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,None_Experiencing,Age_0-9,Age_10-19,Age_20-24,Age_25-59,Age_60+,Gender_Female,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country'].str.split(',', 26, expand=True)
del data['Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,None_Experiencing,Age_0-9,Age_10-19,Age_20-24,Age_25-59,Age_60+,Gender_Female,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country']
del data['Country']
 
# Target features
y = data[['Severity_Mild','Severity_Moderate','Severity_None','Severity_Severe']]

# Input features
X = data.drop(['Severity_Mild','Severity_Moderate','Severity_None','Severity_Severe'], axis=1)

X, y = make_blobs(n_samples=316800, n_features=26, centers=100,
    random_state=0)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2, 
                                                    random_state=123,
                                                    stratify=y)
# DecisionTree
DecisionTree = DecisionTreeClassifier(max_depth=10, min_samples_split=2,
    random_state=0)
# scores = cross_val_score(DecisionTree, X, y, cv=5)
# print('DecisionTree scores.mean: ', scores.mean())

# DecisionTree = DecisionTree.fit(X_train, y_train)
# pred = DecisionTree.predict(X_test)
# print('DecisionTree r2_score: ',r2_score(y_test, pred))

# RandomForest
# RandomForest = RandomForestClassifier(n_estimators=20, max_depth=10,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(RandomForest, X, y, cv=5)
# print('RandomForest scores.mean: ',scores.mean() )
# RandomForest=RandomForest.fit(X_train, y_train)
# predRandomForest = RandomForest.predict(X_test)
# print('RandomForest r2_score: ', r2_score(y_test, predRandomForest))


# # ExtraTrees
# ExtraTrees = ExtraTreesClassifier(n_estimators=20, max_depth=10,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(ExtraTrees, X, y, cv=5)
# print('ExtraTrees scores.mean: ',scores.mean())


DecisionTree scores.mean:  0.8731313131313131
DecisionTree r2_score:  0.7470413301044869
RandomForest scores.mean:  1.0
RandomForest r2_score:  1.0
ExtraTrees scores.mean:  1.0


In [2]:
y_test

array([53, 61, 41, ..., 13, 92, 43])

In [3]:
pred

array([53, 61, 41, ..., 13, 92, 43])

In [4]:
y

array([26, 55, 77, ..., 58, 33, 20])

In [5]:
X

array([[  4.63520962,  -0.11986517,  -9.03063036, ...,   9.04222425,
         -2.11814773,  -5.33539252],
       [ -2.53243808,  -8.00301162,  -0.09664924, ...,   7.2425093 ,
         -3.06191831,   0.22961775],
       [  0.56219424,  -4.94611441,   1.01666879, ...,  -3.91976124,
         -2.84092806,  -8.59753954],
       ...,
       [  9.44405219,   1.06591385,  -9.18291883, ...,  10.96995085,
          8.00230091,  -9.72900617],
       [ -6.45019947,  -2.4576477 ,   7.75237375, ...,  -4.33686808,
         -0.38890834,   5.5046647 ],
       [  1.75260334,  -1.88782491, -10.01933272, ...,   0.58693099,
          7.44950911, -10.81917433]])

In [6]:
data

Fever Tiredness Dry-Cough Difficulty-in-Breathing Sore-Throat  \
0          1         1         1                       1           1   
1          1         1         1                       1           1   
2          1         1         1                       1           1   
3          1         1         1                       1           1   
4          1         1         1                       1           1   
...      ...       ...       ...                     ...         ...   
316795     0         0         0                       0           0   
316796     0         0         0                       0           0   
316797     0         0         0                       0           0   
316798     0         0         0                       0           0   
316799     0         0         0                       0           0   

       None_Sympton Pains Nasal-Congestion Runny-Nose Diarrhea  ...  \
0                 0     1                1          1        1  ...   
1                 0     1                1          1        1  ...   
2                 0     1                1          1        1  ...   
3                 0     1                1          1        1  ...   
4                 0     1                1          1        1  ...   
...             ...   ...              ...        ...      ...  ...   
316795            1     0                0          0        0  ...   
316796            1     0                0          0        0  ...   
316797            1     0                0          0        0  ...   
316798            1     0                0          0        0  ...   
316799            1     0                0          0        0  ...   

       Gender_Female Gender_Male Gender_Transgender Severity_Mild  \
0                  0           1                  0             1   
1                  0           1                  0             1   
2                  0           1                  0             1   
3                  0           1                  0             0   
4                  0           1                  0             0   
...              ...         ...                ...           ...   
316795             0           0                  1             0   
316796             0           0                  1             0   
316797             0           0                  1             0   
316798             0           0                  1             0   
316799             0           0                  1             0   

       Severity_Moderate Severity_None Severity_Severe Contact_Dont-Know  \
0                      0             0               0                 0   
1                      0             0               0                 0   
2                      0             0               0                 1   
3                      1             0               0                 0   
4                      1             0               0                 0   
...                  ...           ...             ...               ...   
316795                 0             0               1                 0   
316796                 0             0               1                 1   
316797                 0             1               0                 0   
316798                 0             1               0                 0   
316799                 0             1               0                 1   

       Contact_No Contact_Yes  
0               0           1  
1               1           0  
2               0           0  
3               0           1  
4               1           0  
...           ...         ...  
316795          1           0  
316796          0           0  
316797          0           1  
316798          1           0  
316799          0           0  

[316800 rows x 26 columns]

In [8]:
# Target features
y = data[['Severity_Mild','Severity_Moderate','Severity_None','Severity_Severe']]

# Input features
X = data.drop(['Severity_Mild','Severity_Moderate','Severity_None','Severity_Severe'], axis=1)

In [12]:
X

Fever Tiredness Dry-Cough Difficulty-in-Breathing Sore-Throat  \
0          1         1         1                       1           1   
1          1         1         1                       1           1   
2          1         1         1                       1           1   
3          1         1         1                       1           1   
4          1         1         1                       1           1   
...      ...       ...       ...                     ...         ...   
316795     0         0         0                       0           0   
316796     0         0         0                       0           0   
316797     0         0         0                       0           0   
316798     0         0         0                       0           0   
316799     0         0         0                       0           0   

       None_Sympton Pains Nasal-Congestion Runny-Nose Diarrhea  ... Age_10-19  \
0                 0     1                1          1        1  ...         0   
1                 0     1                1          1        1  ...         0   
2                 0     1                1          1        1  ...         0   
3                 0     1                1          1        1  ...         0   
4                 0     1                1          1        1  ...         0   
...             ...   ...              ...        ...      ...  ...       ...   
316795            1     0                0          0        0  ...         0   
316796            1     0                0          0        0  ...         0   
316797            1     0                0          0        0  ...         0   
316798            1     0                0          0        0  ...         0   
316799            1     0                0          0        0  ...         0   

       Age_20-24 Age_25-59 Age_60+ Gender_Female Gender_Male  \
0              0         0       0             0           1   
1              0         0       0             0           1   
2              0         0       0             0           1   
3              0         0       0             0           1   
4              0         0       0             0           1   
...          ...       ...     ...           ...         ...   
316795         0         0       1             0           0   
316796         0         0       1             0           0   
316797         0         0       1             0           0   
316798         0         0       1             0           0   
316799         0         0       1             0           0   

       Gender_Transgender Contact_Dont-Know Contact_No Contact_Yes  
0                       0                 0          0           1  
1                       0                 0          1           0  
2                       0                 1          0           0  
3                       0                 0          0           1  
4                       0                 0          1           0  
...                   ...               ...        ...         ...  
316795                  1                 0          1           0  
316796                  1                 1          0           0  
316797                  1                 0          0           1  
316798                  1                 0          1           0  
316799                  1                 1          0           0  

[316800 rows x 22 columns]

In [13]:
y

Severity_Mild Severity_Moderate Severity_None Severity_Severe
0                  1                 0             0               0
1                  1                 0             0               0
2                  1                 0             0               0
3                  0                 1             0               0
4                  0                 1             0               0
...              ...               ...           ...             ...
316795             0                 0             0               1
316796             0                 0             0               1
316797             0                 0             1               0
316798             0                 0             1               0
316799             0                 0             1               0

[316800 rows x 4 columns]

In [14]:
X, y = make_blobs(n_samples=316800, n_features=26, centers=100,
    random_state=0)

In [15]:
X

array([[  4.63520962,  -0.11986517,  -9.03063036, ...,   9.04222425,
         -2.11814773,  -5.33539252],
       [ -2.53243808,  -8.00301162,  -0.09664924, ...,   7.2425093 ,
         -3.06191831,   0.22961775],
       [  0.56219424,  -4.94611441,   1.01666879, ...,  -3.91976124,
         -2.84092806,  -8.59753954],
       ...,
       [  9.44405219,   1.06591385,  -9.18291883, ...,  10.96995085,
          8.00230091,  -9.72900617],
       [ -6.45019947,  -2.4576477 ,   7.75237375, ...,  -4.33686808,
         -0.38890834,   5.5046647 ],
       [  1.75260334,  -1.88782491, -10.01933272, ...,   0.58693099,
          7.44950911, -10.81917433]])

In [16]:
y

array([26, 55, 77, ..., 58, 33, 20])